### ISSUE TITLE
Clarfication on "don't use /dev/random" Comment

### ISSUE THREAD

**Issue by Natrinicle** [infincia/NetRNG#11]
The comment in question can be found here:
https://github.com/infincia/NetRNG/blob/fab9ec23d4a057713c855da38771983dc1e210bb/netrng/core.py#L85

I'm wondering if there was a rational behind this beyond simply not wanting to feed one system with another system's entropy? Did you experience out of entropy blocks on NetRNG servers or other kinds of issues?

Also, is there a way to mix multiple entropy sources into the server if not using /dev/random or multiple NetRNG server instances? This is the real reason I ask since I would like some way to mix an RNG output with video/audio/etc entropy gathering daemons and /dev/random seems like the easiest way to gather pre-mixed entropy.

**Comment by steveatinfincia** [comment]
> I'm wondering if there was a rational behind this beyond simply not wanting to feed one system with another system's entropy? 

Nope, it's basically a caution against treating `/dev/random` as though it was guaranteed to be wired up to the HWRNG, which is not automatically true unless something like `rngd` or TokenTools is intentionally feeding it, or if the kernel is doing it via something like rdrand/rdseed.

And some HWRNGs are very slow, so you may not want the server itself taking up HWRNG output to ensure all of it is available to clients.

> Also, is there a way to mix multiple entropy sources into the server if not using /dev/random or multiple NetRNG server instances? This is the real reason I ask since I would like some way to mix an RNG output with video/audio/etc entropy gathering daemons and /dev/random seems like the easiest way to gather pre-mixed entropy.

Not built-in, to do that in python it would need to switch over to a multi-producer multi-consumer queue rather than reading directly from `Server.hwrng`. Certainly possible, but that may just be replicating what `/dev/random` would do for you anyway, at least on Linux (I don't think the BSDs allow writing to `/dev/random` or do anything with the input).

In any case, if you can guarantee that `/dev/random` is going to be fed continuously by multiple sources, there shouldn't be any problem having NetRNG read from it.

**Comment by Natrinicle** [comment]
Awesome, that's kinda what I figured the rational was. Thanks for clarifying for me!
